export default {
    SET_STATUS: "SET_STATUS",
    INIT_CONNECTION: "INIT_CONNECTION",
    TOGGLE_CHAT_MODULE: "TOGGLE_CHAT_MODULE",
    TOGGLE_CHAT_MODULE_STORE: "TOGGLE_CHAT_MODULE_STORE",
    SHOW_CHAT_MESSAGE: "SHOW_CHAT_MESSAGE",
    SEND_MESSAGE: "SEND_MESSAGE",
}