export default {
    SET_STATUS: "SET_STATUS",
    INIT_CONNECTION: "INIT_CONNECTION",
    TOGGLE_CHAT_MODULE: "TOGGLE_CHAT_MODULE",
    TOGGLE_CHAT_MODULE_STORE: "TOGGLE_CHAT_MODULE_STORE",
    EMIT_MESSAGE: "EMIT_MESSAGE",
    SET_CURRENT_MESSAGE: 'SET_CURRENT_MESSAGE',
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_HISTORY_RECEIVED: 'MESSAGE_HISTORY_RECEIVED',
    USER_LIST_RECEIVED: 'USER_LIST_RECEIVED',
    EMIT_USER_NAME: 'EMIT_USER_NAME'
}